from PIL import Image
import pathlib

OUTPUT_FOLDER = 'outputs'

def combine_slices(slices, save=False, output_file=f'{OUTPUT_FOLDER}/output.jpg'):
    """
        Concatenates the slices generated by `slice_image_vertically` together.
        To get the same effect in the video, this method is called twice:
        once starting with first slice and skipping every 2nd one and,
        once starting with second slice and skipping every 2nd one.

        :param slices: an iterable containing the image slices
        :param save: boolean indicating if image should be saved.
        :param output_file: file to save the image.
    """
    widths, heights = zip(*(i.size for i in slices))
    total_width = sum(widths)
    total_height = max(heights)

    output_image = Image.new('RGB', (total_width, total_height))
    x_offset = 0

    for image in slices:
        output_image.paste(image, (x_offset, 0))
        x_offset += image.size[0]

    if save:
        pathlib.Path(OUTPUT_FOLDER).mkdir(exist_ok=True)
        output_image.save(output_file)

    return output_image

def slice_image_vertically(original_image, slice_size = 5):
    """
        As shown in the imgur video, this method slices/cuts an image vertically

        :param original_image: Image object of the input image.
        :param slice_size: The size of each slice cutted, I recommend playing a little with that parameter depending on your image.

    """
    w, h = original_image.size
    # Constants, doesn't change as we move left to right.
    top = 0
    bottom = h
    # Variables
    left = 0
    right = slice_size
    slices = []

    while left + slice_size < w:
        slices.append(original_image.crop((left, top, right, bottom)))
        left += slice_size
        right += slice_size

    return slices

def main():
    test_image = pathlib.Path('inputs/doggo.jpg')
    if not test_image.exists():
        print('Image doesn\'t exist, please make sure of the path.')
        return
        
    image = Image.open(test_image)
    number_of_rounds = 2
    file_name = test_image.stem

    for i in range(number_of_rounds):
        slices = slice_image_vertically(image)
        first_half = combine_slices(slices[::2])
        second_half = combine_slices(slices[1::2])
        image = combine_slices([first_half, second_half], True, f'{OUTPUT_FOLDER}{file_name}_output_{i}.jpg')


if __name__ == '__main__':
    main()
